export const KaraokeSongs = [
  { id: 1, name: 'Bohemian Rhapsody', artist: 'Queen' },
  { id: 2, name: 'Sweet Caroline', artist: 'Neil Diamond' },
  { id: 3, name: "Don't Stop Believin'", artist: 'Journey' },
  { id: 4, name: "Livin' on a Prayer", artist: 'Bon Jovi' },
  { id: 5, name: 'I Will Survive', artist: 'Gloria Gaynor' },
  { id: 6, name: 'Hotel California', artist: 'Eagles' },
  { id: 7, name: "Summer of '69", artist: 'Bryan Adams' },
  { id: 8, name: 'Wonderwall', artist: 'Oasis' },
  { id: 9, name: "Don't Stop Me Now", artist: 'Queen' },
  { id: 10, name: 'Hey Jude', artist: 'The Beatles' },
  { id: 11, name: 'Wannabe', artist: 'Spice Girls' },
  { id: 12, name: 'I Want It That Way', artist: 'Backstreet Boys' },
  { id: 13, name: "Livin' la Vida Loca", artist: 'Ricky Martin' },
  { id: 14, name: 'Angels', artist: 'Robbie Williams' },
  { id: 15, name: 'My Heart Will Go On', artist: 'Celine Dion' },
  { id: 16, name: "I'm Gonna Be (500 Miles)", artist: 'The Proclaimers' },
  { id: 17, name: 'Man! I Feel Like a Woman!', artist: 'Shania Twain' },
  { id: 18, name: "Don't Speak", artist: 'No Doubt' },
  { id: 19, name: 'Billie Jean', artist: 'Michael Jackson' },
  { id: 20, name: "Livin' la Vida Loca", artist: 'Ricky Martin' },
]
